"""add retention runs and checkpoints

Revision ID: 5786c265b3fe
Revises: b7bfb3b1fa86
Create Date: 2026-08-29 13:19:15.443494

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5786c265b3fe"
down_revision: str | Sequence[str] | None = "b7bfb3b1fa86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "retention_runs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("cutoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("deleted_count", sa.Integer(), nullable=False),
        sa.Column("checkpoint_hashes", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_retention_runs_organization_id"),
        "retention_runs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_retention_runs_status"), "retention_runs", ["status"], unique=False)
    op.create_table(
        "retention_checkpoints",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("anchor_hash", sa.String(length=64), nullable=False),
        sa.Column("removed_through_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("removed_event_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_retention_checkpoints_application_id"),
        "retention_checkpoints",
        ["application_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_retention_checkpoints_application_id"), table_name="retention_checkpoints"
    )
    op.drop_table("retention_checkpoints")
    op.drop_index(op.f("ix_retention_runs_status"), table_name="retention_runs")
    op.drop_index(op.f("ix_retention_runs_organization_id"), table_name="retention_runs")
    op.drop_table("retention_runs")
    # ### end Alembic commands ###
