"""add dead letter records

Revision ID: b6438fbe232f
Revises: 5786c265b3fe
Create Date: 2026-08-29 13:30:22.297510

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6438fbe232f"
down_revision: str | Sequence[str] | None = "5786c265b3fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dead_letter_records",
        sa.Column("task_name", sa.String(length=160), nullable=False),
        sa.Column("task_id", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("error_type", sa.String(length=160), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_retried_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dead_letter_records_status"), "dead_letter_records", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_dead_letter_records_task_id"), "dead_letter_records", ["task_id"], unique=True
    )
    op.create_index(
        op.f("ix_dead_letter_records_task_name"), "dead_letter_records", ["task_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dead_letter_records_task_name"), table_name="dead_letter_records")
    op.drop_index(op.f("ix_dead_letter_records_task_id"), table_name="dead_letter_records")
    op.drop_index(op.f("ix_dead_letter_records_status"), table_name="dead_letter_records")
    op.drop_table("dead_letter_records")
    # ### end Alembic commands ###
