apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: audittrail-api
  namespace: audittrail
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: audittrail-api
  minReplicas: 2
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: audittrail-worker
  namespace: audittrail
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: audittrail-worker
  minReplicas: 2
  maxReplicas: 12
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
