apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: audittrail-api
  namespace: audittrail
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: audittrail-api
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: audittrail-worker
  namespace: audittrail
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: audittrail-api
      app.kubernetes.io/component: worker
